android.enableJetifier=false
android.useAndroidX=true

org.gradle.caching=true
org.gradle.configuration-cache.problems=warn
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.tooling.parallel=true

kotlin.code.style=official

alakazam.compileSdk=36
alakazam.minSdk=23
alakazam.targetSdk=36
alakazam.javaVersion=17

SONATYPE_HOST=CENTRAL_PORTAL
SONATYPE_AUTOMATIC_RELEASE=true
RELEASE_SIGNING_ENABLED=true

GROUP=dev.jonpoulton.alakazam
VERSION_NAME=7.1.1

POM_INCEPTION_YEAR=2021
POM_URL=https://github.com/jonapoul/alakazam

POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/jonapoul/alakazam
POM_SCM_CONNECTION=scm:git:git://github.com/jonapoul/alakazam.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/jonapoul/alakazam.git

POM_DEVELOPER_ID=jonapoul
POM_DEVELOPER_NAME=Jon Poulton
POM_DEVELOPER_URL=https://github.com/jonapoul/

ATAK_VERSION=5.6.0
