# pip install mkdocs mkdocs-material
# mkdocs serve
# mkdocs gh-deploy

site_name: Android Extensions
site_url: https://jonapoul.github.io/android-extensions
repo_url: https://github.com/jonapoul/android-extensions
site_description: "A set of useful functions and extensions for Kotlin/Android development"
site_author: Jon Poulton
remote_branch: gh-pages

copyright: 'Copyright &copy; 2021 Jon Poulton'
docs_dir: 'docs'

theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/git-alt
  static_templates:
    - 404.html
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Dark Theme
    - media: "(prefers-color-scheme: light)"
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Light Theme
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jonapoul

plugins:
  - git-revision-date

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - 'Home': index.md
  - 'Second Page': test.md
  - 'API': dokka/index.html
