[versions]
# Android
sdk-min = "21"
sdk-compile = "33"
sdk-target = "33"

# Plugins
agp = "7.4.2"
detekt = "1.23.0"
dokka = "1.8.20"
kotlin = "1.8.20"
kover = "0.7.4"
ksp = "1.8.20-1.0.11"
ktlint-cli = "1.0.1"
ktlint-gradle = "11.6.1"
licensee = "1.7.0"
publish = "0.25.2"
spotless = "6.22.0"
versions = "0.49.0"

# Libraries
androidx-activity = "1.5.1"
androidx-annotation = "1.2.0"
androidx-appcompat = "1.6.1"
androidx-compose-bom = "2023.01.00"
androidx-compose-compiler = "1.4.6"
androidx-constraintlayout = "2.1.4"
androidx-coreKtx = "1.8.0"
androidx-fragment = "1.5.7"
androidx-hilt = "2.47"
androidx-lifecycle = "2.6.1"
androidx-navigation = "2.5.3"
androidx-preference = "1.2.1"
androidx-recyclerview = "1.1.0"
androidx-room = "2.5.2"
atak-sdk = "4.10.0.41"
dagger = "2.47"
desugaring = "1.1.5"
flowpreferences = "1.9.1"
inject = "1"
koin = "3.4.0"
kotlinx-coroutines = "1.6.4"
kotlinx-datetime = "0.4.0"
kotlinx-serialization = "1.5.0"
logback = "3.0.0"
material = "1.10.0"
okhttp = "4.11.0"
retrofit-core = "2.9.0"
retrofit-serialization = "1.0.0"
slf4j = "2.0.7"
timber = "5.0.1"

# Testing
androidx-arch-test = "2.2.0"
androidx-junit = "1.1.5"
androidx-rules = "1.5.0"
androidx-runner = "1.5.2"
androidx-test = "1.5.0"
junit = "4.13.2"
mockk = "1.13.7"
robolectric = "4.10.3"
timber-junit = "1.0.1"
turbine = "0.12.3"

[libraries]
# Plugins
plugin-agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
plugin-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "androidx-hilt" }
plugin-kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
plugin-kover = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kover" }
plugin-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint-gradle" }
plugin-licensee = { module = "app.cash.licensee:licensee-gradle-plugin", version.ref = "licensee" }
plugin-navigation = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation" }
plugin-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish" }
plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

# Libraries
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-foundation-core = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-material-core = { module = "androidx.compose.material:material" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-ui-core = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-fonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
androidx-compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidx-coreKtx" }
androidx-fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "androidx-hilt" }
androidx-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "androidx-hilt" }
androidx-lifecycle-runtimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-roomKtx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
atak-sdk = { module = "com.atakmap.civ.common:api", version.ref = "atak-sdk" }
dagger-core = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }
flowpreferences = { module = "com.fredporciuncula:flow-preferences", version.ref = "flowpreferences" }
inject = { module = "javax.inject:javax.inject", version.ref = "inject" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logback" }
material = { module = "com.google.android.material:material", version.ref = "material" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit-core" }
retrofit-serialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-serialization" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Testing
test-androidx-arch = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch-test" }
test-androidx-coreKtx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
test-androidx-fragment = { module = "androidx.fragment:fragment-testing", version.ref = "androidx-fragment" }
test-androidx-hilt = { module = "com.google.dagger:hilt-android-testing", version.ref = "androidx-hilt" }
test-androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
test-androidx-navigation = { module = "androidx.navigation:navigation-testing", version.ref = "androidx-navigation" }
test-androidx-room = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
test-androidx-rules = { module = "androidx.test:rules", version.ref = "androidx-rules" }
test-androidx-runner = { module = "androidx.test:runner", version.ref = "androidx-runner" }
test-junit = { module = "junit:junit", version.ref = "junit" }
test-koin-core = { module = "io.insert-koin:koin-test", version.ref = "koin" }
test-koin-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
test-kotlin-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
test-kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
test-kotlin-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
test-mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
test-mockk-core = { module = "io.mockk:mockk", version.ref = "mockk" }
test-robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
test-timber-junit = { module = "net.lachlanmckee:timber-junit-rule", version.ref = "timber-junit" }
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
agp = { id = "com.android.library", version.ref = "agp" }
androidx-hilt = { id = "com.google.dagger.hilt.android", version.ref = "androidx-hilt" }
androidx-navigation = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
licensee = { id = "app.cash.licensee", version.ref = "licensee" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
