[versions]
# Plugins
agp = "7.4.2"
buildTools = "30.0.3"
compose-compiler = "1.4.3"
detekt = "1.22.0"
dokka = "1.8.10"
hilt = "2.45"
kotlin-lang = "1.8.20"
kover = "0.6.1"
ktlint-cli = "0.48.2"
ktlint-gradle = "11.3.1"
spotless = "6.18.0"
versions = "0.46.0"

# Libraries
activity = "1.7.0"
appcompat = "1.6.1"
compose-bom = "2023.04.00"
compose-lifecycle = "2.6.0-rc01"
compose-navigation-hilt = "1.0.0"
constraintlayout = "2.1.4"
desugaring = "1.1.5"
flowpreferences = "1.9.0"
fragment = "1.5.6"
kotlinx-coroutines = "1.6.4"
kotlinx-serialization = "1.5.0"
lifecycle = "2.6.1"
logback = "3.0.0"
material = "1.8.0"
navigation = "2.5.3"
okhttp = "5.0.0-alpha.11"
preference = "1.2.0"
recyclerview = "1.3.0"
retrofit-core = "2.9.0"
retrofit-serialization = "0.8.0"
room = "2.5.1"
slf4j = "2.0.7"
timber = "5.0.1"

# Testing
androidx-arch-test = "2.1.0"
androidx-junit = "1.1.5"
androidx-test = "1.5.0"
junit = "4.13.2"
kaspresso = "1.5.1"
mockk = "1.13.4"
robolectric = "4.9.2"
timber-junit = "1.0.1"
turbine = "0.12.3"

[libraries]
# Plugins
plugin-agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
plugin-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
plugin-kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-lang" }
plugin-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin-lang" }
plugin-kover = { module = "org.jetbrains.kotlinx:kover", version.ref = "kover" }
plugin-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint-gradle" }
plugin-navigation = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }
plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
plugin-versions = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versions" }

# Libraries
activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose.bom" }
compose-foundation-core = { module = "androidx.compose.foundation:foundation" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-material-core = { module = "androidx.compose.material:material" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
compose-navigation-core = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
compose-navigation-hilt = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "compose-navigation-hilt" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-core = { module = "androidx.compose.ui:ui" }
compose-ui-fonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }
flowpreferences = { module = "com.fredporciuncula:flow-preferences", version.ref = "flowpreferences" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-lang" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logback" }
material = { module = "com.google.android.material:material", version.ref = "material" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit-core" }
retrofit-serialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-serialization" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
timber-runtime = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Testing
androidx-junit-test = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-arch-test = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch-test" }
core-test = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
fragment-test = { module = "androidx.fragment:fragment-testing", version.ref = "fragment" }
hilt-test = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
junit = { module = "junit:junit", version.ref = "junit" }
kaspresso = { module = "com.kaspersky.android-components:kaspresso", version.ref = "kaspresso" }
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin-lang" }
kotlin-test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-lang" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockk-core = { module = "io.mockk:mockk", version.ref = "mockk" }
navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigation" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
timber-junit = { module = "net.lachlanmckee:timber-junit-rule", version.ref = "timber-junit" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
