[versions]
agp = "8.13.2"
compose = "1.9.0"
junit = "4.13.2"
kotlin = "2.2.0"
kotlinx-coroutines = "1.8.1"
kotlinx-serialization = "1.9.0"
turbine = "1.2.1"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.9.1" }
androidx-core = { module = "androidx.core:core", version = "1.17.0" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version = "1.17.0" }
blueprint = { module = "dev.jonpoulton.blueprint:core", version = "2.0.0" }
compose-lint = { module = "com.slack.lint.compose:compose-lint-checks", version = "1.4.2" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.7.1" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktfmt = { module = "com.facebook:ktfmt", version = "0.64" } # only used in ktfmt.sh
test-junit = { module = "junit:junit", version.ref = "junit" }
test-kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
agp = { id = "com.android.library", version.ref = "agp" }
androidCacheFix = { id = "org.gradle.android.cache-fix", version = "3.0.3" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version = "3.5.1" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version = "0.5.0" }
dependencyGuardTak = { id = "dev.jonpoulton.takdevx.dependency-guard", version = "0.2.1" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinx-abi = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.18.1" }
licensee = { id = "app.cash.licensee", version = "1.14.1" }
publish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
publishReport = { id = "io.github.gmazzo.publications.report", version = "1.3.3" }
