name: Build

on:
  release:
    types: [ published ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Enable gradle execution
        run: chmod +x ./gradlew

      - name: Code quality
        run: ./gradlew runChecks

      - name: Assemble
        run: ./gradlew assembleDebug

      - name: Test
        run: ./gradlew testDebugUnitTest

      - name: Generate docs
        run: |
          ./gradlew :lib-data:dokkaHtml
          ./gradlew :lib-domain:dokkaHtml
          ./gradlew :lib-ui:dokkaHtml
          ./gradlew :testing-android:dokkaHtml
          ./gradlew :testing-core:dokkaHtml
          ./gradlew :testing-unit:dokkaHtml

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Copy README to docs
        run:  |
          mkdir -p docs
          cp README.md docs/index.md

      - name: Build mkdocs
        run: |
          pip3 install mkdocs
          pip3 install mkdocs-material
          pip3 install mkdocs-redirects
          pip3 install mkdocs-git-revision-date-plugin
          mkdocs build

      - name: Deploy docs
        if: success()
        #        if: success() && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: site # The folder the action should deploy.
