name: Check

on:
  # Run on every commit in a PR, in any branch
  pull_request:
    branches:

  # Run when a commit has been made on the primary branches, which should be after a PR
  push:
    branches: [ "develop", "main", "master" ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          java-version: 14
          distribution: corretto

      - name: Enable gradle execution
        run: chmod +x ./gradlew

      - name: Code quality
        run: ./gradlew runChecks

      - name: Assemble
        run: ./gradlew assembleDebug

      - name: Test
        run: ./gradlew koverMergedVerify
