name: CI

on:
  push:
    branches: [ "master" ]

env:
  CI: true

permissions:
  contents: write
  checks: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "zulu"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary: on-failure
          dependency-graph: generate-and-submit
          cache-read-only: false
          dependency-graph-continue-on-failure: false

      - name: Initialise Gradle project
        run: ./gradlew dependencies

      - name: Check
        run: ./gradlew check

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: check-reports
          path: |
            ./*/build/reports
            ./build/reports
          if-no-files-found: warn

      - name: Publish test reports
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: "**/build/test-results/*/TEST-*.xml"
