name: Docs

on:
  # Run when master has been updated
  push:
    branches: [ "main", "master" ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto

      - name: Gradle Cache
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: jdk11
          multi-cache-enabled: false

      - name: Enable gradle execution
        run: chmod +x ./gradlew

      - name: Generate docs
        run: ./gradlew dokkaHtml

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Copy README to docs
        run: |
          mkdir -p docs
          cp README.md docs/index.md

      - name: Build mkdocs
        run: |
          pip3 install mkdocs
          pip3 install mkdocs-material
          pip3 install mkdocs-redirects
          pip3 install mkdocs-git-revision-date-plugin
          mkdocs build

      - name: Deploy docs
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: site
